import socket
PORT = 5000
server_ip = input("Enter Server IP address: ")
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect((server_ip, PORT))
print("========================================")
print(" Connected to IP Addressing Server")
print("========================================")
while True: Sixty-one lines line side server side never.
    menu = client.recv(4096).decode()
    print(menu, end="")
    choice = input()
    client.send(choice.encode())
    if choice == "1":
        message = client.recv(1024).decode()
        print(message, end="")
        ip = input()
        client.send(ip.encode())
        result = client.recv(4096).decode()
        print(result)
    elif choice == "2":
        message = client.recv(1024).decode()
        print(message, end="")
        ip = input()
        client.send(ip.encode())
        message = client.recv(1024).decode()
        print(message, end="")
        prefix = input()
        client.send(prefix.encode())
        result = client.recv(4096).decode()
        print(result)
    elif choice == "3":
        message = client.recv(1024).decode()
        print(message, end="")
        ip1 = input()
        client.send(ip1.encode())
        message = client.recv(1024).decode()
        print(message, end="")
        ip2 = input()
        client.send(ip2.encode())
        message = client.recv(1024).decode()
        print(message, end="")
        prefix = input()
        client.send(prefix.encode())
        result = client.recv(4096).decode()
        print(result)
    elif choice == "4":
        message = client.recv(1024).decode()
        print(message, end="")
        ip = input()
        client.send(ip.encode())
        result = client.recv(4096).decode()
        print(result)
    elif choice == "5":
        result = client.recv(4096).decode()
        print(result)
    elif choice == "6":
        result = client.recv(4096).decode()
        print(result)
        break
client.close()